# Implementação de setenças 

USE mysql;
SELECT * FROM user;

-- 1° USUÁRIO

# CRIAÇÃO DE USUÁRIO E IDENTIFICAÇÃO DE SENHA
CREATE USER 'Pedro_Henrique' IDENTIFIED BY 'senha12345';

# EXCLUIR USUÁRIO CASO NECESSÁRIO
# DROP USER 'Pedro_Henrique';

# MOSTRAR QUAIS OS ACESSOS QUE O USUÁRIO POSSUI
SHOW GRANTS FOR 'Pedro_Henrique';

USE netflix_projeto;
# PERMITIR ACESSO DE LEITURA DE TODAS AS TABELAS DO PROJETO
GRANT SELECT ON * TO 'Pedro_Henrique';

-- 2° USUÁRIO

CREATE USER 'Pedro_Silva' IDENTIFIED BY '12345senha';
SHOW GRANTS FOR 'Pedro_Silva';
USE netflix_projeto;
# PERMITIR ACESSO DE LEITURA, INSERÇÃO E MODIFICAÇÃO DE TODAS AS TABELAS DO PROJETO
GRANT SELECT, INSERT, UPDATE  ON * TO 'Pedro_Silva';
SHOW GRANTS FOR 'Pedro_Silva';